version: '3.1'

services:
  nginx:
    build: ./srcs/requirements/nginx
    image: nginx:v1.0
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    env_file:
      - ./srcs/.env
    volumes:
      - ./bwordpresstestvolume:/var/www/html/wordpress
    networks:
      - docker_network
    depends_on:
      - wordpress
  wordpress:
    build: ./srcs/requirements/wordpress
    image: wordpress:v1.0
    container_name: wordpress
    restart: unless-stopped
    env_file:
      - ./srcs/.env
    volumes:
      - ./bwordpresstestvolume:/var/www/html/wordpress
    networks:
      - docker_network
    depends_on:
      - mariadb
  mariadb:
    build: ./srcs/requirements/mariadb
    image: mariadb:v1.0
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - ./srcs/.env
    volumes:
      - ./amariadbtestvolume:/var/lib/mysql
    networks:
      - docker_network

networks:
  docker_network:
    driver: bridge